spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ionecar_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: src/main/resources/static/**,src/main/resources/templates/**
    remote:
      restart:
        enabled: false
web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
          no-store: true
          must-revalidate: true
        static-locations: classpath:/static/
      chain:
        cache: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ionecar.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true




